public without sharing class ARTL_DownloadUploadQMContactController {
    /*@AuraEnabled(Cacheable = true)
    public static List<vlocity_cmt__QuoteMember__c> getQuoteMembersByQuoteId(String quoteId){
        if(String.isNotBlank(quoteId)){
            return [SELECT vlocity_cmt__ServiceAccountId__r.name, vlocity_cmt__ServiceAccountId__c, vlocity_cmt__City__c, vlocity_cmt__State__c, vlocity_cmt__StreetAddress__c,  Id  
                FROM vlocity_cmt__QuoteMember__c
                WHERE vlocity_cmt__QuoteId__c = :quoteId];
        }
        return null;
    }*/
}