/***********************************************************************************************************************************
 * @Author       : Aliya Ameer
 * @Date         : 25/10/2023
 * @Description  : Constants used for the OSSJ New/MACD Classes
 ***********************************************************************************************************************************/
public class XMLConstants {
    public static final Integer LAST_UPDATE_VERSION_NUMBER_VALUE = 1;
    public static final String CLIENT_ID_VALUE = 'SFDC';
    public static final String STATUS_VALUE = 'OK';
    public static final Integer PRIORITY_VALUE = 0;
    public static final String ACTION_VALUE = 'Add';
    public static final String OPERATION_VALUE = 'CREATE';
    public static final String SOURCE_VALUE = 'cpq';
    public static final String CANCELTYPE_VALUE = 'Cancel Order';
    public static final String ORDER = '{http://som.sigma.com}Order';
    public static final String LAST_UPDATE_VERSION_NUMBER = '{http://ossj.org/xml/Common/v1-5}lastUpdateVersionNumber';
    public static final String ACTION = '{http://ossj.org/xml/Common-CBEBi/v1-5}action';
    public static final String ORDERITEMKEY = '{http://som.sigma.com}orderItemKey';
    public static final String ORDERITEMSPECKEY = '{http://som.sigma.com}orderItemSpecKey';
    public static final String DISPLAYID = '{http://som.sigma.com}displayId';
    public static final String OPERATION = '{http://som.sigma.com}operation';
    public static final String SOURCE = '{http://som.sigma.com}source';
    public static final String ENTITY = '{http://som.sigma.com}entity';
    public static final String SUBORDERITEM = '{http://som.sigma.com}subOrderItem';
    public static final String CLIENTID = '{http://ossj.org/xml/OrderManagement/v1-0}clientId';
    public static final String STATUS = '{http://som.sigma.com}status';
    public static final String PRIORITY = '{http://som.sigma.com}priority';
    public static final String ACTIVATIONDATE = '{http://som.sigma.com}activationDate';
    public static final String TYPE = '{http://ossj.org/xml/Common/v1-5}type';
    public static final String PRIMARYKEY = '{http://ossj.org/xml/Common/v1-5}primaryKey';
    public static final String EXTERNALKEY = '{http://som.sigma.com}externalKey';
    public static final String ORDERKEY = '{http://som.sigma.com}orderKey';
    public static final String ORDERSPECKEY = '{http://som.sigma.com}orderSpecKey';
    public static final String CHARACTERISTIC = '{http://som.sigma.com}characteristic';
    public static final String CHARACTERISTICS = '{http://som.sigma.com}characteristics';
    public static final String ENTITYSPECKEY = '{http://som.sigma.com}entitySpecKey';
    public static final String ENTITYKEY = '{http://som.sigma.com}entityKey';
    public static final String RATEATTRIBUTES = '{http://som.sigma.com}rateAttributes';
    public static final String RATEATTRIBUTE = '{http://som.sigma.com}rateAttribute';
    public static final String VALUE = '{http://som.sigma.com}value';
    public static final String NAME = '{http://som.sigma.com}name';
    public static final String RATEVALUE = '{http://som.sigma.com}rateValue';
    public static final String RATESPECKEY = '{http://som.sigma.com}rateSpecKey';
    public static final String RATEKEY = '{http://som.sigma.com}rateKey';
    public static final String ITEM = '{http://som.sigma.com}item';
    public static final String VALUEDETAIL = '{http://som.sigma.com}valueDetail';
    public static final String RATE = '{http://som.sigma.com}rate';
    public static final String ORDERITEM = '{http://som.sigma.com}orderItem';
    public static final String CUSTOMER = '{http://som.sigma.com}customer';
    public static final String CUSTOMERSPECKEY = '{http://som.sigma.com}customerSpecKey';
    public static final String CUSTOMERKEY = '{http://som.sigma.com}customerKey';
    public static final String ORDERID = '{http://som.sigma.com}orderId';
    public static final String CANCELTYPE = '{http://som.sigma.com}type';
}